@startuml
title Moodle
left to right direction
skinparam packageStyle rectangle
actor usuario
actor profesor
actor alumno

rectangle moodle{
	usuario -- (darse alta)
	alumno --|> usuario
	profesor --|> usuario
	(crear nuevo curso) -- profesor
	(crear nuevo curso) .> (darse alta) : include
	(pertenecer grupo) .> (matricular alumnos) : include
	alumno -- (pertenecer grupo)
	(descargar contenido) .> (pertenecer grupo) : extends
	(subir entregas) .> (pertenecer grupo) : include
	(matricular alumnos) -- profesor
	(matricular alumnos) .> (crear nuevo curso) : include
	(subir temario) -- profesor
	(crear entrega) -- profesor
	(subir temario) .> (crear nuevo curso) : include
	(crear entrega) .> (crear nuevo curso) : include
	alumno - (consultar temario)
	(consultar temario) .> (subir temario) : include
	(descargar contenido) <. (consultar temario) : extends
	alumno - (descargar contenido)
	alumno -- (subir entregas)
	(subir entregas) .> (crear entrega) : include
	(evaluar entregas) -- profesor
	(evaluar entregas) <. (subir entregas) : extends
	(crear avisos) -- profesor
	alumno -- (consultar avisos)
	(consultar avisos) <. (crear avisos) : extends
	alumno -- (chat)
	(chat) -- profesor
}

@enduml