@startuml
left to right direction
skinparam packageStyle rectangle
actor socio
actor cliente
actor fabrica
rectangle Proceso_venta {
  (vender productos)  --up-- fabrica
  (elaborar producto) --up-- fabrica
  (vender productos) .> (elaborar producto) : include
  (distribuir producto) .> (elaborar producto) : include
  (vender productos) <... (tienda fisica fabrica) : extends
  (vender productos) <... (web): extends
  (vender productos) <... (tienda fisica) : extends
  (vender productos) <... (otros socios) : extends
  (tienda fisica) <. (lotes productos) : extends
  (realizar pago) .> (vender productos) : include
  socio -down- (vender productos)
  socio -- (distribuir producto)
  socio -- (obtener beneficios)
  (obtener beneficios) ..> (tienda fisica fabrica) : include
  (obtener beneficios) ..> (web) : include
  (web) -- cliente
  (web) <.. (consultar catalogo) : extends
  (web) <.. (consultar precios) : extends
  (web) <.. (hacer pedidos) : extends
  (realizar pago) -- cliente
}
@enduml