@startuml
title Moodle
left to right direction
skinparam packageStyle rectangle
actor usuario
actor profesor
actor alumno

rectangle moodle{
(log in) .> (darse alta) : include
usuario --- (log in)
usuario <|-- alumno
usuario <|-- profesor
profesor -- (gestionar grupo)
profesor -- (crear nuevo curso)
(gestionar grupo) .> (crear nuevo curso) : include
(gestionar grupo) <.. (subir temario) : extends
(gestionar grupo) <.. (crear entrega) :extends
(subir temario) <.. (modificar contenidos) : extends
(subir temario) <.. (eliminar contenidos) : extends
(crear entrega) <. (modificar entrega) : extends
(eliminar entrega) .> (crear entrega) : extends
(crear entrega) <.. (calificar entrega) : extends
(gestionar grupo) <.. (crear avisos): extends
(gestionar grupo) <.. (matricular alumnos) : extends

(pertenecer curso) -- alumno
(matricular alumnos) <.. (pertenecer curso) : include
(consultar temario) ..> (pertenecer curso) : extends
(subir temario) <.. (consultar temario) : include
(consultar temario) <. (descargar contenido) : include
(descargar contenido) ..> (pertenecer curso) : extends
(subir entregas) ..> (pertenecer curso) : extends
(crear entrega) <.. (subir entregas) : include
(calificar entrega) .> (subir entregas) : include
(consultar avisos) ..> (pertenecer curso) : extends
(crear avisos) <.. (consultar avisos) : include
usuario -- (chat)
}

@enduml