@startuml
left to right direction
skinparam packageStyle rectangle
actor socio
actor cliente
actor fabrica
rectangle Proceso_venta {
  (elaborar producto) -right- fabrica
  (retirar producto) ..> (elaborar producto) : include
  (distribuir producto) <. (retirar producto) : extends
  (vender productos) <. (retirar producto) : extends
  (vender productos) ...> (pedido online): extends
  (vender productos) ...> (tienda fisica) : extends
  (vender productos) ...> (otros socios) : extends
  (tienda fisica) .> (lotes productos) : extends
  (pedido online) .> (consultar catalogo) : include
  (realizar pago) .> (vender productos) : include
  socio -- (retirar producto)
  socio -- (obtener beneficios)
  (obtener beneficios) .> (vender productos) : include
  (consultar catalogo) -- cliente
  (realizar pago) - cliente
}
@enduml