@startuml
left to right direction
skinparam packageStyle rectangle
actor socio
actor cliente
actor fabrica
rectangle Embutidos {
  (elaborar producto) -up- fabrica
  (retirar producto) .> (elaborar producto) : include
  (distribuir producto) .> (retirar producto) : include
  (vender productos) <. (retirar producto) : include
  (tienda fisica) <. (vender productos) : extends
  (pedido online) <. (vender productos) : extends
  (otros socios) <. (vender productos) : extends
  (lotes productos) <. (vender productos) : extends
  (pedido online) .> (consultar catalogo) : include
  (realizar pago) <. (vender productos) : extends
  socio -- (vender productos)
  socio -- (distribuir producto)
  socio -- (obtener beneficios)
  (pedido online) -- cliente
  (realizar pago) - cliente
}
@enduml